// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixPluginsObject) DeepCopyInto(out *ApisixPluginsObject) {
	*out = *in
	in.ProxyRewrite.DeepCopyInto(&out.ProxyRewrite)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixPluginsObject.
func (in *ApisixPluginsObject) DeepCopy() *ApisixPluginsObject {
	if in == nil {
		return nil
	}
	out := new(ApisixPluginsObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixPluginsProxyRewrite) DeepCopyInto(out *ApisixPluginsProxyRewrite) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixPluginsProxyRewrite.
func (in *ApisixPluginsProxyRewrite) DeepCopy() *ApisixPluginsProxyRewrite {
	if in == nil {
		return nil
	}
	out := new(ApisixPluginsProxyRewrite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoutes) DeepCopyInto(out *ApisixRoutes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoutes.
func (in *ApisixRoutes) DeepCopy() *ApisixRoutes {
	if in == nil {
		return nil
	}
	out := new(ApisixRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApisixRoutes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoutesIngressRef) DeepCopyInto(out *ApisixRoutesIngressRef) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoutesIngressRef.
func (in *ApisixRoutesIngressRef) DeepCopy() *ApisixRoutesIngressRef {
	if in == nil {
		return nil
	}
	out := new(ApisixRoutesIngressRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoutesList) DeepCopyInto(out *ApisixRoutesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApisixRoutes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoutesList.
func (in *ApisixRoutesList) DeepCopy() *ApisixRoutesList {
	if in == nil {
		return nil
	}
	out := new(ApisixRoutesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApisixRoutesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoutesSpec) DeepCopyInto(out *ApisixRoutesSpec) {
	*out = *in
	in.IngressRef.DeepCopyInto(&out.IngressRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoutesSpec.
func (in *ApisixRoutesSpec) DeepCopy() *ApisixRoutesSpec {
	if in == nil {
		return nil
	}
	out := new(ApisixRoutesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixRoutesStatus) DeepCopyInto(out *ApisixRoutesStatus) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Plugins.DeepCopyInto(&out.Plugins)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixRoutesStatus.
func (in *ApisixRoutesStatus) DeepCopy() *ApisixRoutesStatus {
	if in == nil {
		return nil
	}
	out := new(ApisixRoutesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixServiceRef) DeepCopyInto(out *ApisixServiceRef) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixServiceRef.
func (in *ApisixServiceRef) DeepCopy() *ApisixServiceRef {
	if in == nil {
		return nil
	}
	out := new(ApisixServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreamNode) DeepCopyInto(out *ApisixUpstreamNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreamNode.
func (in *ApisixUpstreamNode) DeepCopy() *ApisixUpstreamNode {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreamNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreamTimeout) DeepCopyInto(out *ApisixUpstreamTimeout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreamTimeout.
func (in *ApisixUpstreamTimeout) DeepCopy() *ApisixUpstreamTimeout {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreamTimeout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreams) DeepCopyInto(out *ApisixUpstreams) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreams.
func (in *ApisixUpstreams) DeepCopy() *ApisixUpstreams {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApisixUpstreams) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreamsList) DeepCopyInto(out *ApisixUpstreamsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApisixUpstreams, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreamsList.
func (in *ApisixUpstreamsList) DeepCopy() *ApisixUpstreamsList {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreamsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApisixUpstreamsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreamsSpec) DeepCopyInto(out *ApisixUpstreamsSpec) {
	*out = *in
	in.ServiceRef.DeepCopyInto(&out.ServiceRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreamsSpec.
func (in *ApisixUpstreamsSpec) DeepCopy() *ApisixUpstreamsSpec {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreamsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApisixUpstreamsStatus) DeepCopyInto(out *ApisixUpstreamsStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]ApisixUpstreamNode, len(*in))
		copy(*out, *in)
	}
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApisixUpstreamsStatus.
func (in *ApisixUpstreamsStatus) DeepCopy() *ApisixUpstreamsStatus {
	if in == nil {
		return nil
	}
	out := new(ApisixUpstreamsStatus)
	in.DeepCopyInto(out)
	return out
}
