apiVersion: extensions/v1beta1
kind: ApisixRoute
metadata:
  creationTimestamp: "2020-06-17T06:10:48Z"
  generation: 2
  name: routename
  namespace: default
  resourceVersion: "3381890389"
  selfLink: /apis/extensions/v1beta1/namespaces/default/apisixroutes/routename
  uid: 110cf621-c59c-45d2-9207-f781f98c2bad
spec:
  ingressRef:
    apiVersion:extensions/v1beta1
    kind: Ingress
    name: ingress-rewrite
    namespace: default
    resourceVersion: "3565793835"
    uid: a11d6d9d-f61d-11e9-8613-4206d1ced1e8
   type: Ingress
status:
  uri: /hello
  host: apisix.org
  priority: 0
  methods: ["GET", "POST"]
  plugins:
    - proxy-rewrite:
      a: b  # demo
  service_protocol: http 
  upstream_id: {$namespace}-{$serviceid}
