# permissions for end users to edit apisixroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisixroutes-editor-role
rules:
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixroutes/status
  verbs:
  - get
