# permissions for end users to view apisixroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisixroutes-viewer-role
rules:
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixroutes/status
  verbs:
  - get
