# permissions for end users to view apisixupstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisixupstreams-viewer-role
rules:
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixupstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.com.my.domain
  resources:
  - apisixupstreams/status
  verbs:
  - get
